# Generated by Django 6.0 on 2026-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_data', models.JSONField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reference_client', models.CharField(blank=True, max_length=100)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('IMP', 'Importación'), ('EXP', 'Exportación')], max_length=10)),
                ('merchandise', models.CharField(blank=True, max_length=255)),
                ('transport', models.CharField(blank=True, max_length=100)),
                ('regimen', models.CharField(blank=True, max_length=100)),
                ('cr_checked', models.BooleanField(default=False)),
                ('vessel', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('executive', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('containers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
