# Generated by Django 6.0 on 2026-01-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_initial'),
        ('shipments', '0002_shipment_mongo_id'),
    ]

    operations = [
    ]
