# Generated by Django 5.2.10 on 2026-01-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_remove_shipment_mongo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='# Contenedor')),
                ('size', models.CharField(max_length=20, verbose_name='Tamaño')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_set', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'db_table': 'containers',
                'ordering': ['id'],
            },
        ),
    ]
