# Generated by Django 5.2.10 on 2026-01-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_migrate_containers_json_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='transport',
            field=models.CharField(choices=[('CAMION', 'Camión'), ('FERROCARRIL', 'Ferrocarril'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
