# Generated by Django 6.0 on 2026-01-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_city_client_company_client_ext_number_and_more'),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden personalizado del paso para este cliente', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Si el paso está activo para este cliente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_steps', to='clients.client', verbose_name='Cliente')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_steps', to='steps.step', verbose_name='Paso')),
            ],
            options={
                'verbose_name': 'Paso del Cliente',
                'verbose_name_plural': 'Pasos del Cliente',
                'db_table': 'client_steps',
                'ordering': ['order', 'step__number'],
                'unique_together': {('client', 'step')},
            },
        ),
    ]
