# Generated by Django 6.0 on 2026-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
    ]
