# Generated by Django 6.0 on 2026-01-16 19:43

import clients.models
import django.db.models.deletion
import seguimiento.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_rfc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('validity_months', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si no tiene vigencia', null=True, verbose_name='Vigencia en Meses')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'db_table': 'document_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_calle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_ciudad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_colonia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Colonia (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_cp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_estado',
            field=models.CharField(blank=True, max_length=255, verbose_name='Estado (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_numero_ext',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número Exterior (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='domicilio_operaciones_numero_int',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número Interior (Operaciones)'),
        ),
        migrations.AddField(
            model_name='client',
            name='expediente_completo',
            field=models.BooleanField(default=False, verbose_name='Expediente Completo'),
        ),
        migrations.AddField(
            model_name='client',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='client',
            name='representante_legal_curp',
            field=models.CharField(blank=True, max_length=18, verbose_name='CURP del Representante Legal'),
        ),
        migrations.AddField(
            model_name='client',
            name='representante_legal_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Representante Legal'),
        ),
        migrations.AddField(
            model_name='client',
            name='representante_legal_rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC del Representante Legal'),
        ),
        migrations.AddField(
            model_name='client',
            name='ultima_verificacion_expediente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Verificación del Expediente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ext_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número Exterior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='int_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número Interior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='locality',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.CreateModel(
            name='ClientManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_type', models.CharField(choices=[('EFOS', 'No aparecer en lista de EFOS'), ('EDOS', 'No aparecer en lista de EDOS'), ('EFOS_EDOS', 'No aparecer en listas EFOS/EDOS'), ('OPERACIONES_INEXISTENTES', 'No realizar operaciones inexistentes'), ('DATOS_VERIDICOS', 'Datos proporcionados son verídicos'), ('CONOCIMIENTO_OBLIGACIONES', 'Conocimiento de obligaciones fiscales'), ('OTRO', 'Otra manifestación')], max_length=30, verbose_name='Tipo de Manifestación')),
                ('content', models.TextField(verbose_name='Texto de la Manifestación')),
                ('signed_by_name', models.CharField(max_length=255, verbose_name='Nombre del Firmante')),
                ('signed_by_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('signature_date', models.DateField(verbose_name='Fecha de Firma')),
                ('signature_place', models.CharField(blank=True, max_length=255, verbose_name='Lugar de Firma')),
                ('signed_document', models.FileField(blank=True, null=True, storage=seguimiento.storage_backends.SecureMediaStorage(), upload_to=clients.models.client_manifest_path, verbose_name='Documento Firmado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manifests', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='clients.clientmanifest', verbose_name='Reemplazada por')),
            ],
            options={
                'verbose_name': 'Manifestación del Cliente',
                'verbose_name_plural': 'Manifestaciones de Clientes',
                'db_table': 'client_manifests',
                'ordering': ['-signature_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('FACHADA', 'Fachada del Inmueble'), ('INTERIOR', 'Interior'), ('MAQUINARIA', 'Maquinaria y Equipo'), ('ALMACEN', 'Almacén'), ('PERSONAL', 'Personal Trabajando'), ('VEHICULOS', 'Vehículos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Fotografía')),
                ('image', models.ImageField(storage=seguimiento.storage_backends.SecureMediaStorage(), upload_to=clients.models.client_photo_path, verbose_name='Fotografía')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('taken_date', models.DateField(blank=True, null=True, verbose_name='Fecha de la Foto')),
                ('location_description', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clients.client', verbose_name='Cliente')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Fotografía del Cliente',
                'verbose_name_plural': 'Fotografías de Clientes',
                'db_table': 'client_photos',
                'ordering': ['photo_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=seguimiento.storage_backends.SecureMediaStorage(), upload_to=clients.models.client_document_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Documento')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='Cliente')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='clients.documentcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Documento del Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'db_table': 'client_documents',
                'ordering': ['category__order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SATVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_efos', models.BooleanField(default=False, verbose_name='En lista EFOS')),
                ('is_in_edos', models.BooleanField(default=False, verbose_name='En lista EDOS')),
                ('sat_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta del SAT')),
                ('verification_method', models.CharField(choices=[('AUTOMATIC', 'Automática'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20, verbose_name='Método de Verificación')),
                ('status', models.CharField(choices=[('LIMPIO', 'Sin irregularidades'), ('PRESUNTO', 'En lista de presuntos (EDOS)'), ('DEFINITIVO', 'En lista definitiva (EFOS)'), ('ERROR', 'Error en consulta')], default='LIMPIO', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('verification_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Verificación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_verifications', to='clients.client', verbose_name='Cliente')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Verificación SAT',
                'verbose_name_plural': 'Verificaciones SAT',
                'db_table': 'sat_verifications',
                'ordering': ['-verification_date'],
            },
        ),
    ]
