# Generated by Django 6.0 on 2026-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('etapa', models.IntegerField(blank=True, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('directory', models.CharField(blank=True, max_length=255)),
                ('imp', models.BooleanField(default=False)),
                ('exp', models.BooleanField(default=False)),
                ('button', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paso',
                'verbose_name_plural': 'Pasos',
                'db_table': 'steps',
                'ordering': ['number'],
            },
        ),
    ]
