# Generated by Django 6.0 on 2026-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
