# Generated by Django 6.0 on 2026-01-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('steps', '0002_step_is_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='department_id',
        ),
        migrations.AddField(
            model_name='step',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='departments.department', verbose_name='Departamento'),
        ),
    ]
