# Generated by Django 6.0 on 2026-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('client', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('responsable', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'db_table': 'revisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
