# Generated by Django 6.0 on 2026-01-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0003_merge_0002_initial_0002_revision_mongo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='mongo_id',
        ),
    ]
