# Generated by Django 6.0 on 2026-01-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackings', '0002_tracking_mongo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='mongo_id',
        ),
    ]
