# Generated by Django 6.0 on 2026-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(blank=True, help_text='Código corto del departamento (ej: OPS, DOC)', max_length=10, null=True, unique=True, verbose_name='Código')),
                ('color', models.CharField(default='#6366F1', help_text='Color hexadecimal para gráficos', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
