# Generated by Django 5.2.10 on 2026-01-16 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_compliance_rgce_1414'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_document_expiring', models.BooleanField(default=True, verbose_name='Email: documentos por vencer')),
                ('email_document_expired', models.BooleanField(default=True, verbose_name='Email: documentos vencidos')),
                ('email_sat_alerts', models.BooleanField(default=True, verbose_name='Email: alertas SAT')),
                ('email_expediente_incomplete', models.BooleanField(default=False, verbose_name='Email: expedientes incompletos')),
                ('expiration_warning_days', models.PositiveIntegerField(default=30, verbose_name='Días de anticipación para alertas de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DOCUMENT_EXPIRING', 'Documento por vencer'), ('DOCUMENT_EXPIRED', 'Documento vencido'), ('DOCUMENT_REJECTED', 'Documento rechazado'), ('EXPEDIENTE_INCOMPLETE', 'Expediente incompleto'), ('SAT_ALERT', 'Alerta SAT (EFOS/EDOS)'), ('SAT_VERIFICATION', 'Verificación SAT completada'), ('GENERAL', 'Notificación general')], default='GENERAL', max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío de email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client', verbose_name='Cliente relacionado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type', 'is_read'], name='notificatio_notific_09a8d2_idx'), models.Index(fields=['related_client', 'is_read'], name='notificatio_related_6bca92_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['priority', 'is_read'], name='notificatio_priorit_60753b_idx')],
            },
        ),
    ]
